name: build-on-commit
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the git repo
        uses: actions/checkout@v3

      - name: Get the latest patch
        run: echo "PATCH=$(ls -1 | tail -n 1 | xargs -I{}  basename {} .sql)" >> $GITHUB_ENV
        working-directory: ./patches

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            digiserve/ab-migration-manager:master,
            digiserve/ab-migration-manager:${{ env.PATCH }}
            